import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/earnpage">EarnPage</Link>
        </li>
        <li>
          <Link to="/registerpagethree">RegisterPageThree</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/supportpage">SupportPage</Link>
        </li>
        <li>
          <Link to="/loginpageone">LoginPageOne</Link>
        </li>
        <li>
          <Link to="/marketplace">Marketplace</Link>
        </li>
        <li>
          <Link to="/registerpagefive">RegisterPageFive</Link>
        </li>
        <li>
          <Link to="/advertisingpage">AdvertisingPage</Link>
        </li>
        <li>
          <Link to="/registerpage">RegisterPage</Link>
        </li>
        <li>
          <Link to="/registerpagetwo">RegisterPageTwo</Link>
        </li>
        <li>
          <Link to="/registerpagefour">RegisterPageFour</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
